(() => {
"use strict";
const firebaseConfig={apiKey:"AIzaSyDvWh3PF3DlSMCBDxcj1IU5QmlTRxQ-B08",authDomain:"allen-c2a7b.firebaseapp.com",projectId:"allen-c2a7b",storageBucket:"allen-c2a7b.firebasestorage.app",messagingSenderId:"457456642027",appId:"1:457456642027:web:0c08e6f19aff38cffa9bae",measurementId:"G-LG3H4L1W82"};
firebase.initializeApp(firebaseConfig);
const auth=firebase.auth(), db=firebase.firestore(), provider=new firebase.auth.GoogleAuthProvider();
const STORAGE_KEY="expense-calculator-v2", defaultState={"categories":["生活用品","汽車","保險","飲食","電話網路","醫療保健","居家","美容美髮","其他"],"items":[]};
const colors=["#4b9cff","#44c78a","#ffb454","#b783ff","#ff6f91","#43c6db","#ffd166","#95d36e","#ff8a65","#7b8cff","#e879f9","#9ca3af"];
let state=loadLocal(), editingId=null, currentUser=null, unsubscribeCloud=null, cloudWriteTimer=null, receivingCloud=false;
const $=id=>document.getElementById(id);
const els={form:$("expenseForm"),name:$("name"),amount:$("amount"),frequency:$("frequency"),category:$("category"),note:$("note"),submit:$("submitBtn"),cancel:$("cancelEditBtn"),formTitle:$("formTitle"),monthlyTotal:$("monthlyTotal"),annualTotal:$("annualTotal"),itemCount:$("itemCount"),largestCategory:$("largestCategory"),largestCategoryMini:$("largestCategoryMini"),rows:$("expenseRows"),empty:$("emptyState"),chart:$("donutChart"),legend:$("legend"),chartBasis:$("chartBasis"),chartTotal:$("chartTotal"),chartTotalLabel:$("chartTotalLabel"),search:$("searchInput"),categoryFilter:$("categoryFilter"),sort:$("sortSelect"),toast:$("toast"),importFile:$("importFile"),login:$("loginBtn"),logout:$("logoutBtn"),authText:$("authText"),authDot:$("authDot"),syncSubtitle:$("syncSubtitle")};

function clone(v){return JSON.parse(JSON.stringify(v))}
function validState(v){return v&&Array.isArray(v.categories)&&Array.isArray(v.items)}
function loadLocal(){try{const v=JSON.parse(localStorage.getItem(STORAGE_KEY)||localStorage.getItem("expense-calculator-v1"));if(validState(v))return v}catch(e){}return clone(defaultState)}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if(currentUser&&!receivingCloud){clearTimeout(cloudWriteTimer);cloudWriteTimer=setTimeout(async()=>{try{await db.doc(`users/${currentUser.uid}`).set({categories:state.categories,items:state.items,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});setSyncStatus("已同步到雲端",true)}catch(e){console.error(e);setSyncStatus("雲端儲存失敗",false);toast("雲端儲存失敗，資料仍保留在本機")}},350)}}
function setSyncStatus(text,online){els.syncSubtitle.textContent=text;els.authDot.classList.toggle("online",!!online)}
function money(v){return new Intl.NumberFormat("zh-TW",{style:"currency",currency:"TWD",maximumFractionDigits:0}).format(Math.round(v||0))}
function annualOf(i){const a=Number(i.amount)||0;return i.frequency==="annual"?a:i.frequency==="quarterly"?a*4:i.frequency==="weekly"?a*52:a*12}
function monthlyOf(i){return annualOf(i)/12}
function frequencyText(f){return {monthly:"每月",annual:"每年",quarterly:"每季",weekly:"每週"}[f]||f}
function totalsByCategory(basis="monthly"){const m={};state.items.forEach(i=>{const v=basis==="annual"?annualOf(i):monthlyOf(i);m[i.category]=(m[i.category]||0)+v});return Object.entries(m).map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value)}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function toast(msg){els.toast.textContent=msg;els.toast.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>els.toast.classList.remove("show"),1800)}
function renderCategories(){const cur=els.category.value;els.category.innerHTML=state.categories.map(c=>`<option value="${escapeHtml(c)}">${escapeHtml(c)}</option>`).join("");if(state.categories.includes(cur))els.category.value=cur;const fc=els.categoryFilter.value;els.categoryFilter.innerHTML='<option value="">所有分類</option>'+state.categories.map(c=>`<option value="${escapeHtml(c)}">${escapeHtml(c)}</option>`).join("");if(state.categories.includes(fc))els.categoryFilter.value=fc}
function renderStats(){const monthly=state.items.reduce((s,i)=>s+monthlyOf(i),0),annual=state.items.reduce((s,i)=>s+annualOf(i),0);els.monthlyTotal.textContent=money(monthly);els.annualTotal.textContent=money(annual);els.itemCount.textContent=state.items.length;const cats=totalsByCategory();if(cats.length){els.largestCategory.textContent=cats[0].name;els.largestCategoryMini.textContent=`${money(cats[0].value)}／月，占 ${monthly?(cats[0].value/monthly*100).toFixed(1):0}%`}else{els.largestCategory.textContent="—";els.largestCategoryMini.textContent="尚無資料"}}
function filteredItems(){const q=els.search.value.trim().toLowerCase(),cat=els.categoryFilter.value,sort=els.sort.value;const arr=state.items.filter(i=>(!q||i.name.toLowerCase().includes(q)||(i.note||"").toLowerCase().includes(q))&&(!cat||i.category===cat));arr.sort((a,b)=>sort==="monthly-asc"?monthlyOf(a)-monthlyOf(b):sort==="name-asc"?a.name.localeCompare(b.name,"zh-Hant"):sort==="category-asc"?a.category.localeCompare(b.category,"zh-Hant"):monthlyOf(b)-monthlyOf(a));return arr}
function renderTable(){const items=filteredItems();els.rows.innerHTML=items.map(i=>`<tr><td><strong>${escapeHtml(i.name)}</strong>${i.note?`<div style="color:var(--muted);font-size:12px;margin-top:4px">${escapeHtml(i.note)}</div>`:""}</td><td><span class="badge">${escapeHtml(i.category)}</span></td><td>${frequencyText(i.frequency)}</td><td class="num">${money(i.amount)}</td><td class="num">${money(monthlyOf(i))}</td><td class="num">${money(annualOf(i))}</td><td><div class="actions"><button class="icon-btn" data-edit="${i.id}">編輯</button><button class="icon-btn delete" data-delete="${i.id}">刪除</button></div></td></tr>`).join("");els.empty.classList.toggle("hidden",items.length!==0)}
function drawChart(){const basis=els.chartBasis.value,data=totalsByCategory(basis),total=data.reduce((s,d)=>s+d.value,0),canvas=els.chart,rect=canvas.getBoundingClientRect(),dpr=Math.max(1,window.devicePixelRatio||1),size=Math.max(280,Math.round(rect.width||320));canvas.width=size*dpr;canvas.height=size*dpr;const ctx=canvas.getContext("2d");ctx.scale(dpr,dpr);const cx=size/2,cy=size/2,r=size*.40,inner=size*.25;ctx.clearRect(0,0,size,size);if(!total){ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.arc(cx,cy,inner,0,Math.PI*2,true);ctx.fillStyle="#2b3038";ctx.fill();els.legend.innerHTML='<div class="empty">新增支出後會顯示分類占比。</div>'}else{let start=-Math.PI/2;data.forEach((d,n)=>{const a=d.value/total*Math.PI*2;ctx.beginPath();ctx.arc(cx,cy,r,start,start+a);ctx.arc(cx,cy,inner,start+a,start,true);ctx.closePath();ctx.fillStyle=colors[n%colors.length];ctx.fill();start+=a});els.legend.innerHTML=data.map((d,n)=>`<div class="legend-row"><span class="dot" style="background:${colors[n%colors.length]}"></span><span class="legend-name">${escapeHtml(d.name)}</span><span class="legend-value"><b>${money(d.value)}</b><small>${(d.value/total*100).toFixed(1)}%</small></span></div>`).join("")}els.chartTotal.textContent=money(total);els.chartTotalLabel.textContent=basis==="annual"?"每年總支出":"每月總支出"}
function renderAll(){renderCategories();renderStats();renderTable();requestAnimationFrame(drawChart)}
function resetForm(){editingId=null;els.form.reset();els.frequency.value="monthly";if(state.categories.length)els.category.value=state.categories[0];els.formTitle.textContent="新增支出";els.submit.textContent="新增支出";els.cancel.classList.add("hidden")}

async function startCloud(user){if(unsubscribeCloud)unsubscribeCloud();const ref=db.doc(`users/${user.uid}`);try{const snap=await ref.get();if(!snap.exists){await ref.set({categories:state.categories,items:state.items,updatedAt:firebase.firestore.FieldValue.serverTimestamp()})}else if(validState(snap.data())){receivingCloud=true;state={categories:snap.data().categories,items:snap.data().items};localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderAll();receivingCloud=false}unsubscribeCloud=ref.onSnapshot(s=>{if(!s.exists||!validState(s.data()))return;receivingCloud=true;state={categories:s.data().categories,items:s.data().items};localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderAll();receivingCloud=false;setSyncStatus("已連線，修改會自動同步",true)},e=>{console.error(e);setSyncStatus("同步連線失敗",false)})}catch(e){console.error(e);setSyncStatus("無法讀取雲端資料",false);toast("請確認 Firebase 授權網域與安全規則")}}
auth.onAuthStateChanged(user=>{currentUser=user||null;els.login.classList.toggle("hidden",!!user);els.logout.classList.toggle("hidden",!user);els.authText.textContent=user?(user.displayName||user.email):"未登入";if(user)startCloud(user);else{if(unsubscribeCloud)unsubscribeCloud();unsubscribeCloud=null;setSyncStatus("尚未登入；目前使用本機儲存。",false)}});
els.login.addEventListener("click",async()=>{try{await auth.signInWithPopup(provider)}catch(e){console.error(e);if(["auth/popup-blocked","auth/cancelled-popup-request","auth/operation-not-supported-in-this-environment"].includes(e.code))await auth.signInWithRedirect(provider);else alert("登入失敗："+e.message)}});
els.logout.addEventListener("click",()=>auth.signOut());

els.form.addEventListener("submit",e=>{e.preventDefault();const name=els.name.value.trim(),amount=Number(els.amount.value),category=els.category.value;if(!name||!Number.isFinite(amount)||amount<0||!category)return toast("請完整填寫支出資料");const item={id:editingId||crypto.randomUUID(),name,amount,frequency:els.frequency.value,category,note:els.note.value.trim()};if(editingId){const n=state.items.findIndex(i=>i.id===editingId);if(n>=0)state.items[n]=item;toast("支出已更新")}else{state.items.push(item);toast("支出已新增")}saveState();resetForm();renderAll()});
els.cancel.addEventListener("click",resetForm);
els.rows.addEventListener("click",e=>{const edit=e.target.closest("[data-edit]"),del=e.target.closest("[data-delete]");if(edit){const i=state.items.find(x=>x.id===edit.dataset.edit);if(!i)return;editingId=i.id;els.name.value=i.name;els.amount.value=i.amount;els.frequency.value=i.frequency;els.category.value=i.category;els.note.value=i.note||"";els.formTitle.textContent="編輯支出";els.submit.textContent="儲存修改";els.cancel.classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"})}if(del){const i=state.items.find(x=>x.id===del.dataset.delete);if(i&&confirm(`確定刪除「${i.name}」？`)){state.items=state.items.filter(x=>x.id!==i.id);saveState();renderAll();toast("支出已刪除")}}});
$("addCategoryBtn").addEventListener("click",()=>{const v=prompt("請輸入新分類名稱：");if(v===null)return;const n=v.trim();if(!n)return;if(state.categories.includes(n)){els.category.value=n;return toast("此分類已存在")}state.categories.push(n);saveState();renderCategories();els.category.value=n;toast("分類已新增")});
$("deleteCategoryBtn").addEventListener("click",()=>{
  const category=els.category.value;
  if(!category)return toast("請先選擇要刪除的分類");
  if(state.categories.length<=1)return toast("至少必須保留一個分類");
  const affected=state.items.filter(i=>i.category===category);
  const replacement=state.categories.includes("其他")&&category!=="其他"?"其他":state.categories.find(c=>c!==category);
  const message=affected.length
    ? `「${category}」目前有 ${affected.length} 筆支出。確定刪除分類，並將這些支出移到「${replacement}」嗎？`
    : `確定刪除分類「${category}」嗎？`;
  if(!confirm(message))return;
  if(affected.length)state.items.forEach(i=>{if(i.category===category)i.category=replacement});
  state.categories=state.categories.filter(c=>c!==category);
  saveState();
  renderAll();
  els.category.value=replacement;
  toast(affected.length?`分類已刪除，${affected.length} 筆支出已移到「${replacement}」`:`分類「${category}」已刪除`);
});
[els.search,els.categoryFilter,els.sort].forEach(el=>el.addEventListener(el.tagName==="INPUT"?"input":"change",renderTable));els.chartBasis.addEventListener("change",drawChart);window.addEventListener("resize",()=>requestAnimationFrame(drawChart));
$("exportBtn").addEventListener("click",()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`支出備份_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)});
$("importBtn").addEventListener("click",()=>els.importFile.click());els.importFile.addEventListener("change",async()=>{const f=els.importFile.files[0];if(!f)return;try{const d=JSON.parse(await f.text());if(!validState(d))throw Error();state=d;saveState();resetForm();renderAll();toast("備份已匯入並同步")}catch(e){alert("備份檔格式不正確。")}finally{els.importFile.value=""}});
$("resetBtn").addEventListener("click",()=>{if(confirm("確定重設？這會清除所有支出，並恢復預設分類。")){state=clone(defaultState);saveState();resetForm();renderAll();toast("已重設")}});
renderAll();
})();
